# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to NPM

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
          cache: 'yarn'
          registry-url: https://registry.npmjs.org
      - name: Install yarn dependencies
        run: yarn install
      - name: Compile code
        run: yarn tsc
      - name: Build package
        run: yarn build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}